import "~/styles/globals.css";
import { Rubik } from "next/font/google";
import Navigation from "~/components/Navigation";

const font = Rubik({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "NextJS Page Transitions",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicons.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${font.variable} flex min-h-screen flex-col bg-stone-100`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
